/**
 * scripts/createSamplePdf.js
 *
 * Run this script ONCE to generate a sample fillable PDF template at
 * templates/form.pdf.  The template contains AcroForm text fields that
 * match the sample CSV columns.
 *
 * Usage:
 *   node scripts/createSamplePdf.js
 *
 * Requires pdf-lib (already in dependencies).
 */

'use strict';

require('dotenv').config();

const fs   = require('fs');
const path = require('path');
const { PDFDocument, rgb, StandardFonts } = require('pdf-lib');

async function createSampleTemplate() {
  const doc  = await PDFDocument.create();
  const page = doc.addPage([595.28, 841.89]); // A4

  const font     = await doc.embedFont(StandardFonts.HelveticaBold);
  const fontReg  = await doc.embedFont(StandardFonts.Helvetica);
  const { width, height } = page.getSize();
  const form = doc.getForm();

  // ── Title ──────────────────────────────────────────────────────────────
  page.drawText('Student Application Form', {
    x: 50, y: height - 60,
    size: 20, font, color: rgb(0.1, 0.3, 0.6),
  });
  page.drawLine({
    start: { x: 50, y: height - 70 },
    end:   { x: width - 50, y: height - 70 },
    thickness: 1, color: rgb(0.4, 0.4, 0.4),
  });

  // Helper: create a labelled text field
  function addField(label, fieldName, x, y, w = 200, h = 22) {
    page.drawText(label, {
      x, y: y + 6, size: 10, font: fontReg, color: rgb(0.2, 0.2, 0.2),
    });
    const field = form.createTextField(fieldName);
    field.addToPage(page, {
      x, y: y - h,
      width: w, height: h,
      borderWidth: 1,
      borderColor: rgb(0.5, 0.5, 0.5),
      backgroundColor: rgb(0.97, 0.97, 1),
    });
  }

  // ── Fields ─────────────────────────────────────────────────────────────
  addField('Full Name',         'full_name',   50, height - 120, 460);
  addField('Date of Birth',     'date_of_birth', 50, height - 180, 200);
  addField('Application ID',    'app_id',       280, height - 180, 230);
  addField('Email Address',     'email',        50, height - 240, 460);
  addField('Phone Number',      'phone',        50, height - 300, 200);
  addField('Course / Programme','course',       280, height - 300, 230);
  addField('Address',           'address',      50, height - 360, 460);
  addField('City',              'city',         50, height - 420, 200);
  addField('State',             'state',        280, height - 420, 100);
  addField('Postal Code',       'postal_code',  410, height - 420, 100);

  // ── Footer ─────────────────────────────────────────────────────────────
  page.drawText('Generated by Bulk PDF Form Generator', {
    x: 50, y: 30, size: 8, font: fontReg, color: rgb(0.6, 0.6, 0.6),
  });

  const pdfBytes = await doc.save();

  const outPath = path.join(__dirname, '..', 'templates', 'form.pdf');
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, pdfBytes);

  console.log(`✔  Sample template written to: ${outPath}`);
  console.log(`   Fields: full_name, date_of_birth, app_id, email, phone, course,`);
  console.log(`           address, city, state, postal_code`);
}

createSampleTemplate().catch(err => {
  console.error('Failed to create sample PDF:', err.message);
  process.exit(1);
});
